# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudunits2-dev libv8-3.14-dev
cache: packages

