# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y libudunits2-dev libv8-3.14-dev libgdal-dev libgeos-dev libproj-dev libudunits2-dev liblwgeom-dev
cache: packages

